### Register User

POST http://localhost:8080/register
Content-Type: application/json

{
    "customerFirstName":"khokho",
    "customerLastName":"mayer",
    "customerDateOfBirth":"2000",
    "customerGender":"M",
    "customerAddress":"Fanar",
    "customerTelephoneNumber":"03532816",
    "customerEmail":"charbel-@gmail.com",
    "customerPassword":"password"
}

### Login User

POST http://localhost:8080/login
Content-Type: application/json

{
    "customerEmail":"tester@gmail.com",
    "customerPassword":"password"
}


### Logout User

POST http://localhost:8080/logout



### Ping login

GET http://localhost:8080/login