### Get all reservations

GET http://localhost:8080/reservations


### Make a reservation

POST http://localhost:8080/reservations
Content-Type: application/json

{
    "ticketDateOfPurchase":"2020-12-01",
    "departureDate":"2020-12-19",
    "reservationRoomId":"4",
    "reservationTravelPlanId":"1"
}