### Get all reservations

GET http://localhost:8080/reservations


### Make a reservation

POST http://localhost:8080/reservations
Content-Type: application/json

{
    "departureDate":"2020-12-19",
    "reservationRoomId":"1",
    "reservationTravelPlanId":"2"
}